namespace Thorium.API.Lexing;

public enum TokenType {
    // OPERATORS -- 1 Char
    PLUS, MINUS, MULT, DIV, MOD, EQUAL, BIN_AND, BIN_OR, BIN_XOR, BIN_NOT,
    
    // OPERATORS -- 2 Char
    POW, PLUS_EQUAL, MINUS_EQUAL, MULT_EQUAL, DIV_EQUAL, MOD_EQUAL, INCREMENT, DECREMENT, LEFT_SHIFT, RIGHT_SHIFT,
    
    // OPERATORS -- 3 Char
    POW_EQUAL,
    
    // GROUPING
    L_PAREN, R_PAREN, L_BRACE, R_BRACE, L_BRACKET, R_BRACKET,
    
    // MISC -- 1 Char
    COMMA, DOT, SEMICOLON,
    
    // LOGICAL OPERATORS
    BANG, BANG_EQUAL, AND, OR, EQUAL_EQUAL,
    
    // RELATIONAL OPERATORS
    LESS, GREATER, LESS_EQUAL, GREATER_EQUAL,
    
    // LITERALS
    NUMBER, IDENTIFIER, STRING_LIT, CHAR_LIT,
    
    // CONTROL FLOW
    IF, ELIF, ELSE, WHILE, FOR, CONTINUE, BREAK, RETURN,
    
    // COMPOSITIONAL KEYWORDS
    CLASS, SUPER, THIS, NULL, TRUE, FALSE,
    
    // TYPES
    INT, LONG, DOUBLE, BOOL, STRING_TYPE, CHAR_TYPE, OBJECT, TYPECAST,
    
    // TEMP
    PRINT,
    
    EOF,
}